from naoqi import ALProxy
import time
import almath

posture = ALProxy("ALRobotPosture","169.254.108.110",9559)
motion = ALProxy("ALMotion","169.254.108.110",9559)
tts = ALProxy("ALTextToSpeech","169.254.108.110",9559)
motion.wakeUp()
posture.goToPosture("Stand",0.8)
motion.setAngles(['LShoulderPitch','RShoulderPitch','LShoulderRoll','RShoulderRoll'],[0.0,50*almath.TO_RAD,almath.TO_RAD*40,almath.TO_RAD*-40],0.1)
time.sleep(2.8)
motion.setAngles(['LShoulderRoll','RShoulderRoll'],[-5*almath.TO_RAD,5.0*almath.TO_RAD],0.1)
time.sleep(4.5)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[0*almath.TO_RAD,50*almath.TO_RAD],0.1)
time.sleep(1.0)
motion.setAngles(['LShoulderPitch','RShoulderPitch'],[50*almath.TO_RAD,0*almath.TO_RAD],0.1)
time.sleep(1.0)
tts.say("ok, that was my performance, thank you for watching me")
tts.say("see you again in our exebition in june 2015")
motion.rest()